### PR TITLE
Allow specifying DSN explicitly for external postgres

### LINKED ISSUE #44: Postgresql password not being properly output in the DSN
### Expected vs actual behavior

I expect the DSN in secrets to include the configured password.
-
`<no value>` is output where the password should be.

### Steps to reproduce the bug

1. disable the embedded postgresql install `.Values.deploy.postgresql.enable=false`
2. configure the required postgresql variables for building the DSN 
3. run `helm template .` and inspect the `paralus-db` secret.

### Are you using the latest version of the project?

```
  chart:
    spec:
      chart: ztka
      version: "~> 0.1.0"
      sourceRef:
        kind: HelmRepository
        name: paralus
```

-

### Notes

Will open a PR fixing this issue but it also contains other changes to allow the explicit setting of the postgresql DSN

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

### PR DESCRIPTION
**Pull request by meain**
### What does this PR change?

Allow specifying the DSN explicitly. Fixes #44.
This PR is an extension of https://github.com/paralus/helm-charts/pull/45

### Checklist

I confirm, that I have...

- [x] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [x] Updated `CHANGELOG.md`
- [x] Ran [`helm-docs`](https://github.com/norwoodj/helm-docs) to update docs for chart (if values.yaml file was changed)

### CODE REVIEW

**Review by niravparikh05 — APPROVED** [review]
LGTM

**Review by akshay196 — DISMISSED** [review]

**Comment by akshay196** [comment]
@meain Can we merge this or are we waiting on something?

**Comment by meain** [comment]
@akshay196 Since we will need the latest version of paralus/paralus for DSN to work, I wanted to wait for that to have a release(will happen today) and use the new tag here.

**Review by akshay196 — APPROVED** [review]

**Review by niravparikh05 — APPROVED** [review]
LGTM

**Pull request merged**
